### ISSUE TITLE
[Question]: about the bar's position

### ISSUE THREAD

**Issue by PerilousBooklet** [gimcnuk/lite-xl-fullbar#2]
The `fullbar` appears above the DocView and not in the top part of the RootView:

![image](https://github.com/user-attachments/assets/39b98a47-7ba5-4c6f-b2ea-10cb8826af33)

In the project's README however, the bar appears in the top part of the RootView:

![image](https://github.com/user-attachments/assets/1beb3fb5-09fb-4ec3-9e7b-f234e3202db1)

Is this an intended behaviour?

**Comment by gimcnuk** [comment]
try to change first line of _%USERDIR%/.config/lite-xl/plugins/fullbarview.lua_ to 

`-- mod-version:3 --lite-xl 2.1.4 --priority:90`

**Comment by PerilousBooklet** [comment]
That fixed it, thanks!

**Comment by PerilousBooklet** [comment]
As reference for my future plugins, can I ask you how you learned to do this?

**Comment by gimcnuk** [comment]
plugins are loaded by name and priority, details you can found in _lite-xl/data/core/init.lua_

`function core.load_plugins()`

default priority = 100, less is faster in queue
