### ISSUE TITLE
QUESTION: about the `tabler-icons` icon font.

### ISSUE THREAD

**Issue by PerilousBooklet** [gimcnuk/lite-xl-fullbar#3]
Can you please tell me where I can find the SVG source files of the `tabler-icons` font ?
I want to propose a PR to modify the repo structure as it was done for the other icon font plugins found in `lite-xl-plugins`.

**Comment by gimcnuk** [comment]
as it calls

https://github.com/tabler/tabler-icons

**Comment by PerilousBooklet** [comment]
Thanks!
